def build_error_email_html(ticket_number, error_message):
    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;">
        <div style="max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 8px; border: 1px solid #ddd;">

            <h2 style="color: #b30000; text-align: center;">
                ⚠️ EOPYY Error Alert
            </h2>

            <p style="font-size: 16px;">
                A processing error occurred for the following ticket:
            </p>

            <div style="background: #fafafa; padding: 15px; border-radius: 6px; border: 1px solid #eee; margin-bottom: 20px;">
                <strong>Ticket Number:</strong> {ticket_number}<br>
                <strong>Timestamp:</strong> NOW()
            </div>

            <h3 style="color: #b30000;">Error Details</h3>
            <pre style="background: #fff0f0; padding: 15px; border-radius: 6px; border: 1px solid #ffcccc; white-space: pre-wrap; font-size: 14px;">
{error_message}
            </pre>

            <p style="font-size: 14px; color: #555; margin-top: 30px;">
                This message was automatically generated by the EOPYY Worker.
            </p>

        </div>
    </body>
    </html>
    """
