services:
  - type: web
    name: eopyy-backend
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase: neondb
      - key: API_KEY
        sync: false
      - key: API_HEADER
        value: X-API-Key

  - type: worker
    name: eopyy-worker-realtime
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: DATABASE_URL
        fromDatabase: neondb

  - type: worker
    name: eopyy-worker-batch
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.worker_batch
    envVars:
      - key: DATABASE_URL
        fromDatabase: neondb

databases:
  - name: neondb
